-- Run once in the Supabase SQL Editor.
create table if not exists public.priority_reminder_log (
  id bigint generated by default as identity primary key,
  reminder_date date not null unique,
  task_count integer not null,
  created_at timestamptz not null default now()
);

alter table public.priority_reminder_log enable row level security;

-- Store the Resend key and sender in Supabase Edge Function secrets, not in this file:
-- RESEND_API_KEY
-- RESEND_FROM_EMAIL (must be a verified Resend sender/domain address)
-- PRIORITY_CRON_SECRET (same random value stored in Supabase Vault as priority_cron_secret)
-- SUPABASE_SERVICE_ROLE_KEY (Supabase provides this to Edge Functions automatically)

-- The job runs hourly in UTC; the Edge Function itself sends only during the
-- 10:00-10:14 Europe/London window, so daylight-saving changes remain correct.
create extension if not exists pg_net;
select cron.schedule(
  'priority-portal-p1-reminder-hourly',
  '0 * * * *',
  $$
  select net.http_post(
    url := 'https://wxojqxxdwdlwmgbfoefq.supabase.co/functions/v1/send-p1-reminder',
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'x-priority-cron-secret', (select decrypted_secret from vault.decrypted_secrets where name = 'priority_cron_secret' limit 1)
    ),
    body := '{}'::jsonb
  );
  $$
);
